name: "Askgod discourse YAML validator"
description: "Validates YAML files format and integrity for discourse posts"
inputs:
  path_to_files:
    description: "Directory containing all YAML files"
    required: true
    default: "scenario"
  api_users:
    description: "Comma separated list of valid API users for YAML files"
    required: false
    default: ""
runs:
  using: "node20"
  main: "index.js"
